"""1

Revision ID: ef60feec7ef5
Revises: 
Create Date: 2023-01-05 19:08:07.327253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef60feec7ef5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_cumfig', sa.Column('deals_performed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_cumfig', 'deals_performed')
    # ### end Alembic commands ###
